name: Hello Actions
on: [workflow_dispatch]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "olÃ¡, gh actions - ${{github.repository}} - ${{github.actor}} - ${{github.ref}} - ${{github.sha}} - ${{github.event_name}}"
      - name: Generate Status file
        run: echo "Ultimo build por ${{github.actor}} em $(date)" > status.txt
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: status
          path: status.txt

